version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - tax-thiefs-web-{{ checksum "tax-thiefs-web/package.json" }}

      - run: |
          cd tax-thiefs-web
          npm install

      - save_cache:
          paths:
            - tax-thiefs-web/node_modules
          key: tax-thiefs-web-{{ checksum "tax-thiefs-web/package.json" }}

      - run: |
          cd tax-thiefs-web
          npm run build

  deploy:
    docker:
      - image: circleci/node:12.14

    working_directory: ~/repo

    steps:
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export S3="s3://tax-thiefs.com"' >> $BASH_ENV

      - checkout

      - restore_cache:
          keys:
            - tax-thiefs-web-{{ checksum "tax-thiefs-web/package.json" }}

      - run: |
          cd tax-thiefs-web
          npm install

      - save_cache:
          paths:
            - tax-thiefs-web/node_modules
          key: tax-thiefs-web-{{ checksum "tax-thiefs-web/package.json" }}

      - setup_remote_docker

      - run: |
          cd tax-thiefs-web
          npm run build
          echo $AWS_KEY
          docker create -e AWS_ACCESS_KEY_ID=$AWS_KEY -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET --name uploader anigeo/awscli s3 cp /build $S3 --recursive --acl public-read
          docker cp ./build uploader:/
          docker start -a -i uploader
          docker rm uploader

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
